name: Update Configs
permissions: write-all

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: cd scripts && pip install -r requirements.txt
      
    - name: Install beautifulsoup4
      run: pip install beautifulsoup4
      
    - name: Run Config script and save output to file
      run: cd scripts && python app.py
      
    - name: Check for local changes
      run: |
        echo "Checking for local changes..."
        git status
        
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Updated scripts and files every 5 minutes ⚡️" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
