name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every 10 minutes
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Stash any local changes
      run: git stash
      
    - name: Install dependencies
      run: cd scripts && pip install -r requirements.txt

      
    - name: Install beautifulsoup4
      run: pip install beautifulsoup4

    - name: Run Config script and save output to file
      run: cd scripts && python app.py
      
    - name: Run Warp script and save output to file
      run: cd scripts && python warp.py
      
    - name: Run Splitter script and save output to file
      run: cd scripts && python sort.py

    - name: Run the script to get the actual subscribtion link of vmess port 80
      run: cd scripts && python try.py

    - name: Run the script to test for all working vmess
      run: cd scripts && python working.py

    - name: Run the script to remove duplicate vmess
      run: cd scripts && python reducer.py

    - name: Run the script to get the actual subscribtion link of vmess port 80
      run: cd scripts && python create_subscription_link.py

    - name: Run the script to retest the vmess and remove non working ones
      run: cd scripts && python retest.py

    - name: Check changes
      run: |
        echo "Checking the changes made..."
        git status
        ls -l scripts/
        
    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions"
        author_email: "actions@github.com"
        message: "Updated 4 minutes Ago ⚡️"
        add: "."
        push: "https://github.com/TalesOrigin/configuration.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
