name: Retest Subscription Link
permissions: write-all

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Stash any local changes
      run: git stash
      
    - name: Install dependencies
      run: cd scripts && pip install -r requirements.txt

    - name: Run Retest script
      run: cd scripts && python retest.py
      
    - name: Run the script to get the actual subscription link of vmess port 80
      run: cd scripts && python create_subscription_link.py

    - name: Check changes
      run: |
        echo "Checking the changes made..."
        git status
        ls -l scripts/
        
    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions"
        author_email: "actions@github.com"
        message: "Retested subscription links every 30 minutes ⚡️"
        add: "."
        push: "https://github.com/TalesOrigin/configuration.git"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
